**Working with arrays and matrices**

In [1]:
import numpy as np

In [3]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [7]:
arr.trace()

30

In [5]:
a = np.array([4,5,12,3])
b = np.array([6,2,4,5])
x = np.dot(a,b)
x

97

In [6]:
y = a.dot(b)
y

97

In [8]:
d = arr.dot(b)
d

array([ 25,  93, 161, 229])

In [10]:
d = np.vdot(a,b)
d

97

In [12]:
i = np.inner(arr, a)
i

array([ 38, 134, 230, 326])

In [13]:
m = np.matmul(a,b)
m

97

**linlang library**

In [14]:
from numpy import linalg

In [17]:
arr = np.arange(1,17).reshape((4,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
d = linalg.det(arr)
d

0.0

In [20]:
linalg.eig(arr)

(array([ 3.62093727e+01, -2.20937271e+00, -3.18863232e-15, -1.34840081e-16]),
 array([[-0.15115432,  0.72704996,  0.50370019, -0.06456091],
        [-0.34923733,  0.28320876, -0.8319577 , -0.31932112],
        [-0.54732033, -0.16063243,  0.15281481,  0.83232496],
        [-0.74540333, -0.60447363,  0.17544269, -0.44844294]]))

In [21]:
a = np.array([[1,2],[3,4]])  
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
linalg.qr(arr)

(array([[-0.06019293, -0.83449195,  0.27017127, -0.47645303],
        [-0.30096463, -0.45762462, -0.00510124,  0.83664447],
        [-0.54173634, -0.08075729, -0.80031132, -0.24392987],
        [-0.78250805,  0.29611005,  0.5352413 , -0.11626158]]),
 array([[-1.66132477e+01, -1.82986497e+01, -1.99840516e+01,
         -2.16694536e+01],
        [ 0.00000000e+00, -1.07676380e+00, -2.15352761e+00,
         -3.23029141e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.61650912e-15,
          1.61650912e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          4.93038066e-32]]))

In [24]:
linalg.svd(arr)

(array([[-0.13472212, -0.82574206,  0.38124745, -0.39325613],
        [-0.3407577 , -0.4288172 , -0.21521411,  0.80850658],
        [-0.54679327, -0.03189234, -0.71331411, -0.43724476],
        [-0.75282884,  0.36503251,  0.54728078,  0.02199431]]),
 array([3.86226568e+01, 2.07132307e+00, 7.60977226e-16, 3.86063773e-16]),
 array([[-0.4284124 , -0.47437252, -0.52033264, -0.56629275],
        [ 0.71865348,  0.27380781, -0.17103786, -0.61588352],
        [ 0.28255951, -0.72647617,  0.6052738 , -0.16135714],
        [-0.46921223,  0.41500889,  0.57761893, -0.52341558]]))

**Random Number generation**

In [25]:
np.random.normal(4,2, (4,4))

array([[3.54507217, 3.05758982, 9.13444234, 1.36224907],
       [3.2981206 , 4.61516726, 2.85013102, 0.57178826],
       [6.32179317, 6.01612006, 5.41223888, 5.20449992],
       [3.37126601, 5.97277157, 7.31300497, 4.78882886]])

In [26]:
np.random.gamma((4,4))

array([3.16650379, 2.77522735])

In [28]:
np.random.seed(5)
np.random.rand()

0.22199317108973948

In [39]:
a = arr.reshape((2,2,2,2))

In [42]:
a

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [40]:
x = a.reshape((4,4), order='F')
x

array([[ 1,  3,  2,  4],
       [ 9, 11, 10, 12],
       [ 5,  7,  6,  8],
       [13, 15, 14, 16]])

In [41]:
y = a.reshape((4,4), order='C')
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [44]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**Concatenation**

In [52]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [53]:
a

array([[1, 2],
       [3, 4]])

In [54]:
b

array([[5, 6],
       [7, 8]])

In [59]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [60]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [61]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.r_[a,b]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
np.c_[a,b]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Array splitting**

In [66]:
x = np.array([1,3,4,2,5,6,22,1])
x

array([ 1,  3,  4,  2,  5,  6, 22,  1])

In [67]:
np.split(x, [3])

[array([1, 3, 4]), array([ 2,  5,  6, 22,  1])]

In [68]:
np.split(x, [3,5])

[array([1, 3, 4]), array([2, 5]), array([ 6, 22,  1])]

In [69]:
l = np.arange(0,7,2)
l

array([0, 2, 4, 6])

In [70]:
np.split(x,l)

[array([], dtype=int64),
 array([1, 3]),
 array([4, 2]),
 array([5, 6]),
 array([22,  1])]

In [71]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [72]:
np.split(a,[1])

[array([[1, 2]]), array([[3, 4]])]