**More about NumPy Functions**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,34,5,23,52])
arr2 = np.array([44,12,21,3,12,22])

In [3]:
arr1

array([ 1,  2, 34,  5, 23, 52])

In [4]:
arr2

array([44, 12, 21,  3, 12, 22])

In [5]:
res = []
for i,_ in enumerate(arr1):
  res.append(arr1[i]+arr2[i])
res

[45, 14, 55, 8, 35, 74]

**where in NumPy**

In [6]:
marks = np.array([50,76,34,89,98,43])
marks

array([50, 76, 34, 89, 98, 43])

In [7]:
np.where(marks >= 50, 'Pass', 'Fail')

array(['Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [8]:
salary = np.array([120000, 76000, 90000, 110000, 670000])
salary

array([120000,  76000,  90000, 110000, 670000])

In [9]:
x = np.where(salary < 100000, salary * 1.5, salary * 1.2)
x

array([144000., 114000., 135000., 132000., 804000.])

In [11]:
x.dtype

dtype('float64')

In [15]:
arr = np.arange(1,101).reshape((10,10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Tanspose

In [16]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [17]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Mean

In [18]:
y = np.array([1,3,5,2,6])
y.mean()

3.4

cumsum

In [19]:
y.cumsum()

array([ 1,  4,  9, 11, 17])

cumprod

In [20]:
y.cumprod()

array([  1,   3,  15,  30, 180])

Methods for boolean array

In [21]:
genders = np.array(['Male', 'Female', 'Male', 'Male', 'Female'])
genders

array(['Male', 'Female', 'Male', 'Male', 'Female'], dtype='<U6')

In [24]:
arr = genders == 'Male'
arr

array([ True, False,  True,  True, False])

In [25]:
arr.sum()

3

In [26]:
arr = genders == 'Female'
arr.sum()

2

In [27]:
arr.any()

True

In [28]:
arr.all()

False

In [32]:
arr = np.array([2,4,6,7])
arr

array([2, 4, 6, 7])

In [33]:
x = arr % 2 == 0
x

array([ True,  True,  True, False])

Sort

In [34]:
arr = np.array([2, 23, 4, 6, 11, 7])
arr

array([ 2, 23,  4,  6, 11,  7])

In [38]:
s = arr.sort()
s

In [40]:
# sort in reverse
s = arr[::-1]
s

array([23, 11,  7,  6,  4,  2])

In [41]:
arr = np.array([43, 11, 23, 33, 11, 43, 4])
arr

array([43, 11, 23, 33, 11, 43,  4])

In [44]:
u = np.unique(arr)

**File input/output**

In [46]:
np.save('data', u) # save to u to file

In [47]:
# load data
content = np.load('data.npy')
content

array([ 4, 11, 23, 33, 43])

In [48]:
students = np.array(['Ali', 'Ahmed', 'Sarim'])
marks = np.array([99, 85, 70])

In [49]:
students

array(['Ali', 'Ahmed', 'Sarim'], dtype='<U5')

In [50]:
marks

array([99, 85, 70])

In [51]:
# saving multiple arrays in file
np.savez('marksheet', st = students, m = marks)

In [54]:
data = np.load('marksheet.npz')
data['st']

array(['Ali', 'Ahmed', 'Sarim'], dtype='<U5')

In [55]:
data['m']

array([99, 85, 70])