**NumPy**

Comparison of time between Numpy Array and List in *Python*

Numpy Array

In [1]:
import numpy as np

In [11]:
np_arr = np.arange(10000)
%time for i in range(10) : result = np_arr * 5

CPU times: user 554 µs, sys: 30 µs, total: 584 µs
Wall time: 594 µs


List in Python

In [10]:
py_list = range(10000)
%time for i in range(10) : result = [i*5 for i in py_list]

CPU times: user 15 ms, sys: 0 ns, total: 15 ms
Wall time: 17.1 ms


NumPy Functions

In [16]:
one_d_zeros = np.zeros((5))
one_d_zeros

array([0., 0., 0., 0., 0.])

In [15]:
two_d_zeros = np.zeros((5,2))
two_d_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
one_d_ones = np.ones((5))
one_d_ones

array([1., 1., 1., 1., 1.])

In [18]:
two_d_ones = np.ones((5,2))
two_d_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
two_d_ones * 5

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [22]:
two_d_ones + 5

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [23]:
two_d_ones - 5

array([[-4., -4.],
       [-4., -4.],
       [-4., -4.],
       [-4., -4.],
       [-4., -4.]])

In [24]:
two_d_ones * 5 ** 2

array([[25., 25.],
       [25., 25.],
       [25., 25.],
       [25., 25.],
       [25., 25.]])

In [27]:
np_arr = np.arange(1,21)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
np_arr * 5

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [30]:
np_arr.shape

(20,)

In [35]:
np_array = np.zeros((3,4,3))
np_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
np_array.shape

(3, 4, 3)

In [40]:
np_x = np.array([4,5,11,44,6,7,22,664])
np_x

array([  4,   5,  11,  44,   6,   7,  22, 664])

In [41]:
np_x.shape

(8,)

In [53]:
np_x = np_x.reshape((2,4))
np_x

array([[  4,   5,  11,  44],
       [  6,   7,  22, 664]])

In [51]:
np_x.shape

(2, 4)

In [52]:
np_x.ndim

2

Accessing numpy array elements

In [54]:
np_x[1,3]

664

In [56]:
z = np_x.reshape((2,2,2))
z

array([[[  4,   5],
        [ 11,  44]],

       [[  6,   7],
        [ 22, 664]]])

In [57]:
z.shape

(2, 2, 2)

In [61]:
z[1,1]

array([ 22, 664])

In [62]:
z[0,0,1]

5

Slicing

In [67]:
y = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
y[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
y.shape

(4, 4)

In [71]:
y[0:3,1]

array([ 2,  6, 10])

In [74]:
y[1,1:]

array([6, 7, 8])

In [75]:
y[::,0]

array([ 1,  5,  9, 13])

Vectorized Operations

In [76]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [77]:
x

array([1, 2, 3, 4])

In [78]:
y

array([5, 6, 7, 8])

In [79]:
x+y

array([ 6,  8, 10, 12])

In [80]:
x**y

array([    1,    64,  2187, 65536])

In [82]:
x/y

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [81]:
x*y

array([ 5, 12, 21, 32])

Working with Shapes

11111

11111

11111

11111

11111

In [97]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Shape:**

00000

11111

11111

11111

00000

In [98]:
arr[0]=0
arr[-1]=0
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

**Shape:**

11111

10001

10001

10001

10001

In [104]:
arr = np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])